# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://junglie85.github.io/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

disqusShortname = "junglie85"
googleAnalytics = "G-6T5CSHL8L5"

[outputs]
home = ["HTML", "RSS", "JSON"]
